[weaviate]
url = "http://localhost:8080"

[mongodb]
uri = "mongodb://localhost:27017"
db = "sample_mflix"
collection = "movies"

[app]
default_results = 5
similarity_metrics = ["cosine", "dot"]
search_algorithms = ["hybrid", "BM25F", "vector"]
